name: Project-Template
hw_version: '1.2'
sw_version: '0.0.1'

build_settings:
  development:
    processor: 18F57K42
    programmer: Pickit4
    defines:
      - DEVELOPMENT


  release:
    processor: 18F57K42
    programmer: Pickit4
    defines:
      - DEVELOPMENT